library(ISLR)
library(MASS)
attach(Auto)
pairs(Auto)
cor(Auto[,-9])
lm.fit=lm(mpg~.-name, data=Auto)
summary(lm.fit)
par(mfrow=c(2,2))
plot(lm.fit)
lm.fit3=lm(mpg~weight+displacement*year+origin, data=Auto)
lm.fit2=lm(mpg~year+I(year^2), data=Auto)
plot(lm.fit2)
